### ISSUE TITLE
AmwandengaSubmission.spec.js: Galley creation:   Unexpected behavior in Cypress Versions  in OJS 3.3.0

### ISSUE THREAD

**Issue by withanage** [pkp/pkp-github-actions#10]
# Unexpected Behavior in Cypress

## Explanation

In certain runs, Cypress does not completely fill input fields with an "esecape" character.

## Example 1 Amwandenga
For  editing galley field, cypress does not write the Full "Version 2"

Cypress adds only  "PDF Ver" for "PDF Version 2"

 https://github.com/pkp/ojs/blob/stable-3_3_0/cypress/tests/data/60-content/AmwandengaSubmission.spec.js#L266
![Data suite tests -- Editor must create version to make changes (failed)](https://github.com/pkp/pkp-github-actions/assets/1921992/55e6913b-38d7-4ece-a571-c75951fd0368)

## Example 2  CCoriono

![Data suite Ccorino -- Sends to review and selects pre-existing keywords (failed)](https://github.com/pkp/pkp-github-actions/assets/1921992/8d6154cc-2070-40cd-883e-f1b9a06af85e)

 

## Info
-  If there are no spaces,  in "Version 2"  the tests pass in a predetermined way. e.g. V2 instead of Version 2

## Tested versions

Cypress :5.6,  8, 9

| Node/ Chrome Version |5.6 | 8|  9  | 
| ---- | ---- | ---- | ---- |
|117 | :x:  | :x:  | :x: |
| 121|  :x:  | :x: | :x:|
| 122|  :x:  |  :x:| :x: |
| Latest-Beta|  :x:  |  :x:| :x: |

**Comment by asmecher** [comment]
@withanage, I was able to run the tests on `stable-3_3_0` in Cypress as-is, which suggests it's a timing problem rather than an outright bug in the tests.

For the first problem (`AmwandengaSubmission.spec.js`), does it break consistently at that same point for you (either in Github Actions or a local runner)?

For the second (`CCorionoSubmission.spec.js`), did you run this test in isolation? It's necessary for the `AmwandengaSubmission.spec.js` test to run first in order for the keywords to be present in the database as expected. Otherwise the autocomplete won't respond as expected to the keyword input in the test script.
